name: 'Terraform'

on:
  push:
    branches:
    - "main"
  pull_request:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OCI_TENANCY_OCID: ${{ secrets.TENANCY_OCID }}
  OCI_COMPARTMENT_OCID: ${{ secrets.COMPARTMENT_OCID }}
  OCI_USER_OCID: ${{ secrets.USER_OCID }}
  OCI_PUBKEY_FINGERPRINT: ${{ secrets.FINGERPRINT }}
  OCI_PRIVKEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
  
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
      

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
    - name: source env
      run: source env-vars
    - name: Terraform validate
      run: terraform validate
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
